version: '3'

services:
  django:
    build: .
    container_name: django
    command: python mysite/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: db
    volumes:
      - pgdata:/var/lib/postgresql/data/volumes

  vue-nuxt:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - django
    environment:
      - API_URL=http://django:8000

volumes:
  pgdata: