<<<<<<< HEAD
version: '3'

services:
  django:
    build: .
    container_name: django
    command: python mysite/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres
=======
services:
  django:
    # Сборка образа для сервиса django из текущей директории
    build: .
    # Задание имени контейнера для сервиса django
    container_name: django
    # Задание команды, которую нужно запустить при запуске контейнера для сервиса django
    command: python mysite/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    # Открытие порта на хостовой машине и перенаправление на порт в контейнере
    ports:
      - 8000:8000
    networks:
      - mynetwork
    depends_on:
      - db
  db:
    # Использование готового образа postgres
    image: postgres
    # Задание переменных окружения для контейнера с postgres
>>>>>>> e063247 (Доработка Nuxt3)
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
<<<<<<< HEAD
    container_name: db
    volumes:
      - pgdata:/var/lib/postgresql/data/volumes

  vue-nuxt:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
=======
      # Задание имени контейнера для сервиса pgdb
    container_name: db
    # Связывание тома с директорией в контейнере для сохранения данных postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - mynetwork

  nuxt:
    build:
      context: ../main-vue-nuxt/nuxt-vue-site
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - mynetwork
>>>>>>> e063247 (Доработка Nuxt3)
    depends_on:
      - django
    environment:
      - API_URL=http://django:8000

<<<<<<< HEAD
volumes:
  pgdata:
=======
networks:
  mynetwork:
    driver: bridge
    
volumes:
  pgdata:
>>>>>>> e063247 (Доработка Nuxt3)
